ci:
  autofix_commit_msg: "ci: pre-commit auto fixes"
  autoupdate_commit_msg: "ci: pre-commit auto update"
  autoupdate_schedule: "monthly"
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
        name: Fix End of Files
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
        name: Check Blanket "#noqa"
      - id: python-check-blanket-type-ignore
        name: 'Check Blanket "#type:ignore"'
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        name: Upgrade Python Syntax
  - repo: https://github.com/crate-ci/typos
    rev: v1.3.4
    hooks:
      - id: typos
        name: Check Typos
        args: []
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        name: Format Source Code
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sort Imports
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        name: Type Check
        args: []
        # As `mypy` runs in an isolated environment, it is necessary to manually specify
        # some libraries of the current (poetry) environment for `mypy` to work properly.
        additional_dependencies:
          - arrow==1.2.1
          - httpx==0.21.3
          - hypothesis==6.35.0
          - importlib-metadata==4.10.0
          - playwright==1.18.1
          - pydantic==1.9.0
          - pytest==6.2.5
          - pytest-asyncio==0.17.0
          - starlette==0.17.1
          - types-dataclasses==0.6.4
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: Lint
        additional_dependencies:
          - darglint==1.8.1
          - flake8-bugbear==22.1.11
          - flake8-builtins==1.5.3
          - flake8-comprehensions==3.8.0
          - flake8-datetimez==20.10.0
          - flake8-debugger==4.0.0
          - flake8-docstrings==1.6.0
          - flake8-eradicate==1.2.0
          - flake8-print==4.0.0
          - flake8-too-many==0.1.4
          - pep8-naming==0.12.1
          - tryceratops==1.0.1
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.3
    hooks:
      - id: commitizen
        name: Check Commit Message
        stages: [commit-msg]
