ci:
  autofix_commit_msg: "ci: pre-commit auto fixes"
  autoupdate_commit_msg: "ci: pre-commit auto update"
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.27.0
    hooks:
      - id: nitpick-check
        name: Nitpick Check
        always_run: true
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
        name: Check Blanket "#noqa"
      - id: python-check-blanket-type-ignore
        name: 'Check Blanket "#type:ignore"'
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.28.0
    hooks:
      - id: pyupgrade
        name: Upgrade Python Syntax
  - repo: https://github.com/crate-ci/typos
    rev: typos-v0.7.4
    hooks:
      - id: typos
        name: Check Typos
        args: []
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        name: Format Source Code
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: Sort Imports
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        name: Type Check
        args: []
        # As `mypy` runs in an isolated environment, it is necessary to manually specify
        # some libraries of the current (poetry) environment for `mypy` to work properly.
        additional_dependencies:
          - arrow==1.1.1
          - httpx==0.19.0
          - hypothesis==6.23.1
          - importlib-metadata==4.8.1
          - pydantic==1.8.2
          - pytest==6.2.5
          - pytest-asyncio==0.15.1
          - starlette==0.16.0
          - types-dataclasses==0.1.7
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: Lint
        additional_dependencies:
          - darglint==1.8.0
          - flake8-bugbear==21.9.2
          - flake8-builtins==1.5.3
          - flake8-comprehensions==3.6.1
          - flake8-datetimez==20.10.0
          - flake8-debugger==4.0.0
          - flake8-docstrings==1.6.0
          - flake8-eradicate==1.1.0
          - flake8-print==4.0.0
          - flake8-too-many==0.1.2
          - pep8-naming==0.12.1
          - tryceratops==0.6.0
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.19.0
    hooks:
      - id: commitizen
        name: Check Commit Message
        stages: [commit-msg]
