default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
        name: Check Blanket "#noqa"
      - id: python-check-blanket-type-ignore
        name: 'Check Blanket "#type:ignore"'
  - repo: https://github.com/crate-ci/typos
    rev: v1.1.6
    hooks:
      - id: typos
        name: Check Typos
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        name: Format Source Code
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: Sort Imports
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        name: Type Check
        args: []
        # As `mypy` runs in an isolated environment, it is necessary to manually specify
        # some libraries of the current (poetry) environment for `mypy` to work properly.
        additional_dependencies:
          - hypothesis==6.14.5
          - pytest==6.2.4
          - rsserpent==0.1.2
          - types-dataclasses==0.1.5
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: Lint
        additional_dependencies:
          - darglint==1.8.0
          - flake8-bugbear==21.4.3
          - flake8-builtins==1.5.3
          - flake8-docstrings==1.6.0
          - flake8-eradicate==1.1.0
          - flake8-expression-complexity==0.0.9
          - flake8-print==4.0.0
          - flake8-too-many==0.1.1
          - mypy-extensions==0.4.3  # required by flake8-functions
          - pep8-naming==0.12.0
          - typing-extensions==3.10.0.0  # required by flake8-functions
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.13
    hooks:
      - id: commitizen
        name: Check Commit Message
        stages: [commit-msg]
