name: Codecov
on: [pull_request, push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Install Dependencies"
        run: |
          pip install --user poetry
          poetry install
      - name: "Generate Coverage Report"
        run: poetry run pytest --cov --cov-report=xml
      - name: "Upload to Codecov.io"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
