name: Test

on:
  pull_request:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/test.yaml'
      - 'poetry.lock'
      - 'rsserpent/**'
      - 'tests/**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      HYPOTHESIS_PROFILE: ci
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Setup Poetry"
        run: |
          pip install --user poetry
          poetry config virtualenvs.in-project true
      - uses: actions/cache@v1
        with:
          path: .venv
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: "Install Dependencies"
        run: |
          poetry install
          poetry run pip install git+https://github.com/RSSerpent/rsserpent-plugin-example.git
      - name: "Generate Coverage Report"
        run: poetry run pytest --cov --cov-report=xml
      - name: "Upload to Codecov.io"
        if: ${{ github.repository == 'RSSerpent/RSSerpent' }}
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
